name: GoogleLanguage
author: thinkphp
current: v1.0
category: request
tags: [json,request,interface,google,translate,language,translator,REST]
docs: https://github.com/thinkphp/google-translate/blob/master/docs/GoogleLanguage.md
demo: http://thinkphp.ro/apps/js-hacks/google-translate/demos/demo2.html